//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommingSoon.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPublisherInfo
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FacebookAccountOrPage { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> NumberOfContent { get; set; }
        public Nullable<int> AvgPricePerCost { get; set; }
        public string MobileNumber { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
    }
}
